name: Test build docker images

on:
  pull_request:

jobs:
  changed_files:
    name: Get changed Dockerfiles
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changes.outputs.matrix}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed Dockerfiles
        id: changes
        run: |
          dockerfile_list_json=$(git diff --name-only --diff-filter=ACMRT \
            ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} \
            | grep Dockerfile$ \
            | jq -Rsc '. / "\n" - [""]' )
          echo "matrix=${dockerfile_list_json}" > $GITHUB_OUTPUT
  
  test_build:
    name: Test build
    runs-on: ubuntu-latest
    needs: changed_files
    strategy:
      fail-fast: false
      matrix: 
        dockerfile: ${{ fromJson(needs.changed_files.outputs.matrix) }}
    if: ${{needs.changed_files.outputs.matrix}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Building dockerfile
        run: |
          set -ex
          # Dockerfile removed since last commit, skip
          if [ ! -f ${{matrix.dockerfile}} ]; then
            echo "File ${{matrix.dockerfile}} not found, skipping"
            exit 0
          fi
          tmpName="test-image-$RANDOM"
          docker build $(dirname ${{matrix.dockerfile}}) --file ${{matrix.dockerfile}} --tag $tmpName
          # Print versions
          if [[ ${{matrix.dockerfile}} == *"silta-php-fpm"* ]]; then
            docker run -t --rm $tmpName php -r 'echo "PHP " . PHP_VERSION;'
          fi
          if [[ ${{matrix.dockerfile}} == *"silta-node"* ]]; then
            docker run -t --rm $tmpName node -v
          fi
